### PR TITLE
Day 12 & tips 16

### PR DESCRIPTION
**Pull request by Norgus**
This tips file is problematic because they changed a lot of things by removing specific types of drugs and specific illnesses.

Personally, I feel like it'd be better to either rip the text for this tips file ALL directly from Higurashi Sui or to just take out voicing on this tip as "not compatible".

I'll provide an updated translation if anyone wants to provide all of the Sui text for these tips (not just the speech parts).

### CODE REVIEW

**Comment by ItaloKnox** [comment]
Take a look at this: https://mega.nz/#!GANzWBZZ!DSdFcfL-wFPyxOHHLK5jkQ2zWCJlgKZueialL1PyLtg
Provided by the anon who ripped the script, I guess that's the full script.

**Comment by Norgus** [comment]
Great, thanks!
Now I need to find me a text editor that doesn't get overloaded by the size of the file! Any recommendations?
notepad++ looked promising until I tried to skip ahead to the point with 自殺を誘発するクスリは which froze it (maybe it'd get there eventually though..)

**Comment by ItaloKnox** [comment]
I'm a big fan of Sublime Text. You can pretty much customize everything, the workflow is pretty good even for managing text.

**Comment by Norgus** [comment]
Great, looks like it can handle the monster text file!
(less keen on possibly having to pay 70 USD for it in the future, though!)

**Pull request merged**
